def elementMap(abbr):
    #https://www.overleaf.com/learn/latex/Using_colors_in_LaTeX
    
    #col, row, color
    elementMap ={ 'H': [0,0,'\\nonmetal']
                 ,'H_{example}': [1,3,'\\nonmetal']
                 ,'He': [0,17,'\\noble']
                 
                 ,'Li': [1,0,'\\alkali_metal']
                 ,'Be': [1,1,'\\alkaline_earth']
                 ,'B': [1,12,'\\metalloid']
                 ,'C': [1,13,'\\nonmetal']
                 ,'N': [1,14,'\\nonmetal']
                 ,'O': [1,15,'\\nonmetal']
                 ,'F': [1,16,'\\halogen']
                 ,'Ne': [1,17,'\\noble']

                 ,'Na': [2,0,'\\alkali_metal']
                 ,'Mg': [2,1,'\\alkaline_earth']
                 ,'Al': [2,12,'\\basic_metal']
                 ,'Si': [2,13,'\\metalloid']
                 ,'P': [2,14,'\\nonmetal']
                 ,'S': [2,15,'\\nonmetal']
                 ,'Cl': [2,16,'\\halogen']
                 ,'Ar': [2,17,'\\noble']
                 
                 ,'K': [3,0,'\\alkali_metal']
                 ,'Ca': [3,1,'\\alkaline_earth']
                 ,'Sc': [3,2,'\\transition_metal']
                 ,'Ti': [3,3,'\\transition_metal']
                 ,'V': [3,4,'\\transition_metal']
                 ,'Cr': [3,5,'\\transition_metal']
                 ,'Mn': [3,6,'\\transition_metal']
                 ,'Fe': [3,7,'\\transition_metal']
                 ,'Co': [3,8,'\\transition_metal']
                 ,'Ni': [3,9,'\\transition_metal']
                 ,'Cu': [3,10,'\\transition_metal']
                 ,'Zn': [3,11,'\\transition_metal']
                 ,'Ga': [3,12,'\\basic_metal']
                 ,'Ge': [3,13,'\\metalloid']
                 ,'As': [3,14,'\\metalloid']
                 ,'Se': [3,15,'\\nonmetal']
                 ,'Br': [3,16,'\\halogen']
                 ,'Kr': [3,17,'\\noble']
                 
                 ,'Rb': [4,0,'\\alkali_metal']
                 ,'Sr': [4,1,'\\alkaline_earth']
                 ,'Y': [4,2,'\\transition_metal']
                 ,'Zr': [4,3,'\\transition_metal']
                 ,'Nb': [4,4,'\\transition_metal']
                 ,'Mo': [4,5,'\\transition_metal']
                 ,'Tc': [4,6,'\\transition_metal']
                 ,'Ru': [4,7,'\\transition_metal']
                 ,'Rh': [4,8,'\\transition_metal']
                 ,'Pd': [4,9,'\\transition_metal']
                 ,'Ag': [4,10,'\\transition_metal']
                 ,'Cd': [4,11,'\\transition_metal']
                 ,'In': [4,12,'\\basic_metal']
                 ,'Sn': [4,13,'\\basic_metal']
                 ,'Sb': [4,14,'\\metalloid']
                 ,'Te': [4,15,'\\metalloid']
                 ,'I': [4,16,'\\halogen']
                 ,'Xe': [4,17,'\\noble']
                 
                 ,'Cs': [5,0,'\\alkali_metal']
                 ,'Ba': [5,1,'\\alkaline_earth']
                 ,'Hf': [5,3,'\\transition_metal']
                 ,'Ta': [5,4,'\\transition_metal']
                 ,'W': [5,5,'\\transition_metal']
                 ,'Re': [5,6,'\\transition_metal']
                 ,'Os': [5,7,'\\transition_metal']
                 ,'Ir': [5,8,'\\transition_metal']
                 ,'Pt': [5,9,'\\transition_metal']
                 ,'Au': [5,10,'\\transition_metal']
                 ,'Hg': [5,11,'\\transition_metal']
                 ,'Tl': [5,12,'\\basic_metal']
                 ,'Pb': [5,13,'\\basic_metal']
                 ,'Bi': [5,14,'\\basic_metal']
                 ,'Po': [5,15,'\\metalloid']
                 ,'At': [5,16,'\\halogen']
                 ,'Rn': [5,17,'\\noble']

                 ,'Fr': [6,0,'\\alkali_metal']
                 ,'Ra': [6,1,'\\alkaline_earth']
                 ,'Rf': [6,3,'\\transition_metal']
                 ,'Db': [6,4,'\\transition_metal']
                 ,'Sg': [6,5,'\\transition_metal']
                 ,'Bh': [6,6,'\\transition_metal']
                 ,'Hs': [6,7,'\\transition_metal']
                 ,'Mt': [6,8,'\\transition_metal']
                 ,'Ds': [6,9,'\\transition_metal']
                 ,'Rg': [6,10,'\\transition_metal']
                 ,'Cn': [6,11,'\\transition_metal']
                 ,'Nh': [6,12,'\\basic_metal']
                 ,'Fl': [6,13,'\\basic_metal']
                 ,'Mc': [6,14,'\\basic_metal']
                 ,'Lv': [6,15,'\\basic_metal']
                 ,'Ts': [6,16,'\\halogen']
                 ,'Og': [6,17,'\\noble']
                 
                 ,'$\\gamma_e$': [7,0,'\\other']
                 ,'$\\gamma_n$': [7,1,'\\other']

                 ,'La': [7,2,'\\lanthanoid']
                 ,'Ce': [7,3,'\\lanthanoid']
                 ,'Pr': [7,4,'\\lanthanoid']
                 ,'Nd': [7,5,'\\lanthanoid']
                 ,'Pm': [7,6,'\\lanthanoid']
                 ,'Sm': [7,7,'\\lanthanoid']
                 ,'Eu': [7,8,'\\lanthanoid']
                 ,'Gd': [7,9,'\\lanthanoid']
                 ,'Tb': [7,10,'\\lanthanoid']
                 ,'Dy': [7,11,'\\lanthanoid']
                 ,'Ho': [7,12,'\\lanthanoid']
                 ,'Er': [7,13,'\\lanthanoid']
                 ,'Tm': [7,14,'\\lanthanoid']
                 ,'Yb': [7,15,'\\lanthanoid']
                 ,'Lu': [7,16,'\\lanthanoid']

                 ,'Ac': [8,2,'\\actinoid']
                 ,'Th': [8,3,'\\actinoid']
                 ,'Pa': [8,4,'\\actinoid']
                 ,'U': [8,5,'\\actinoid']
                 ,'Np': [8,6,'\\actinoid']
                 ,'Pu': [8,7,'\\actinoid']
                 ,'Am': [8,8,'\\actinoid']
                 ,'Cm': [8,9,'\\actinoid']
                 ,'Bk': [8,10,'\\actinoid']
                 ,'Cf': [8,11,'\\actinoid']
                 ,'Es': [8,12,'\\actinoid']
                 ,'Fm': [8,13,'\\actinoid']
                 ,'Md': [8,14,'\\actinoid']
                 ,'No': [8,15,'\\actinoid']
                 ,'Lr': [8,16,'\\actinoid']
                 }
                 
    return elementMap[abbr]
    
